debug = true
seed = 123123

# Tree Settings
[TREE]
  max_segment_probability = 0.1
  branch_split_algorithm = 1
  scale_tree = true
  target_tree_length = 100.0
  resolve_multifurcation = false

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  initial_value = 0.1

[INPUT]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  tree_file = "datasets/tree.newick"

[OUTPUT]
  output_directory = "/output"
  output_directory_append_time = false
  overwrite_output = true 

  tree_out_file = "tree_out.newick"
  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_counts_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  counts_out_file = "counts.csv"

[MCMC]
  generations = "10001"
  alignment_sample_frequency = 250
  position_sample_count = 1
  output_frequency = 100
  print_frequency = 100
  full_update_freq = 1
  base_virtual = 10
  
  triple_recursion = false
  include_alternative_domain = true

[MODEL]
  script_file = "hidden_states.lua"

  step_size = 0.00001

# Nucleotide state
  states = ['a', 't', 'c', 'g']
  sequences_file = "datasets/nucleotide.fasta"

  sequences_out_file = "sequences_out.fasta"
  substitutions_out_file = "substitutions.out"

# Hiddin intrinsic order state
  hidden_sequences_file = "datasets/hidden_state.efasta"

  hidden_sequences_out_file = ""
  hidden_substitutions_out_file = "substitutions.out"

