debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_probability = 0.08
  branch_split_algorithm = 1
  scale_tree = true
  target_tree_length = 1.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  initial_value = 0.5

[INPUT]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  tree_file = "datasets/tree.newick"

[OUTPUT]
  output_directory = "/output"
  tree_out_file = "tree_out.newick"
  output_directory_append_time = false
  overwrite_output = true

  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_out_file.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  substitutions_out_file = "substitutions.out"
  counts_out_file = "counts.csv"

[MCMC]
  generations = "1001"
  full_update_freq = 200
  alignment_sample_frequency = 200
  output_frequency = 100
  print_frequency = 100
  position_sample_count= 20

  base_virtual = 0
  triple_recursion = true

[MODEL]
  script_file = "discrete_parameters.lua"

  sequences_file = "datasets/nucleotide.fasta"

  sequences_out_file = ""
  substitutions_out_file = "substitutions.out"

  states = ['a', 't', 'c', 'g']
  number_of_categories = 10
  lower_limit = 0.0000000001
  upper_limit = 0.04