debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_length = 0.08
  branch_split_algorithm = 1

# Uniformization Constant
[UNIFORMIZATION]
  threshold = 0.002
  max_step = 0.001

[DATA]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  substitution_model_file = "model.lua"

  sequences_file = "A0A060D0R0.fasta"
  tree_file = "A0A060D0R0.newick"
[OUTPUT]
  output_directory = "/output"
  tree_out_file = "tree_out.newick"
  sequences_out_file = "sequences_out.fasta"
  parameters_out_file = "parameters_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  substitutions_out_file = "substitutions.out"
  log_out_file = "run.log"

[MCMC]
  generations = 10001
  tree_sample_frequency = 200
  output_frequency = 200
  print_frequency = 500

[MODEL]
  states = ["A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"]

