debug = true
seed = 23241234

# Tree Settings
[TREE]
  max_segment_probability = 0.08
  branch_split_algorithm = 1
  scale_tree = false
  target_tree_length = 100.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  initial_value = 0.2

[INPUT]
  tree_file = "datasets/tree.newick"

[OUTPUT]
  output_directory = "/output"
  output_directory_append_time = false
  overwrite_output = true
 
  tree_out_file = "tree_out.newick"
  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_counts_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  counts_out_file = "counts.csv"
  log_out_file = "run.log"

[MCMC]
  generations = "1000000"
  position_sample_count = 6
  full_update_freq = 100
  alignment_sample_frequency = 2500
  output_frequency = 1000
  print_frequency = 1000

  base_virtual = 0
  triple_recursion = true

[MODEL]
  script_file = "basic_model_expand.lua"

  sequences_file = "datasets/nucleotide.fasta"

  sequences_out_file = ""
  substitutions_out_file = "substitutions.out"

  step_size = 0.0005
  states = ['a', 't', 'c', 'g']