debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_length = 0.08
  branch_split_algorithm = 1
  scale_factor = 1.0
  resolve_root = true

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  initial_value = 0.1
  threshold = 0.005
  max_step = 0.001
  sample_frequency = 250
  refresh_tree_on_update = false

[DATA]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  substitution_model_file = "model.lua"

  sequences_file = "test_data/5taxon_same.fasta"
  #tree_file = "test_data/5taxon_tips_only.newick"
  #tree_file = "test_data/5taxon_all_names.newick"
  tree_file = "test_data/5taxon_unrooted.newick"
  #tree_file = "test_data/5taxon_with_bootstrap.newick"
  #tree_file = "test_data/5taxon_with_branchsplit.newick"

[OUTPUT]
  # If an output file is given as "", then no data will be saved to that file.
  # This can be useful as the output of simPLEX can get quite large.
  output_directory = "./s1_test_run/"
  tree_out_file = "tree_out.newick"
 # tree_out_file = ""
  sequences_out_file = "sequences_out.fasta"
 # sequences_out_file = ""
  parameters_out_file = "parameters_out.csv"
  #parameters_out_file = ""
  rate_vectors_out_file = "rate_vectors_out.csv"
  #rate_vectors_out_file = ""
  likelihood_out_file = "likelihoods_out.csv"
  #likelihood_out_file = ""
  substitutions_out_file = "substitutions.out"
  log_out_file = "run.log"

[MCMC]
  generations = 10001
  tree_sample_frequency = 500
  output_frequency = 100
  print_frequency = 250
  
[MODEL]
  #states = ["A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"]
  states = ["N", "F"]
  parameter_type = "discrete"
  num_categories = 4

