debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_probability = 0.025
  branch_split_algorithm = 1
  scale_tree = false
  target_tree_length = 100.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  sample_frequency = 2000
  refresh_tree_on_update = true
  initial_value = 0.2
  threshold = 0.01
  max_step = 0.005

[INPUT]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  tree_file = "dataset/G1LLZ1_Archaea.newick"

[OUTPUT]
  output_directory = "/output"
  output_directory_append_time = false
  overwrite_output = true
 
  tree_out_file = "tree_out.newick"
  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_out_counts.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  counts_out_file = "counts.csv"
  log_out_file = "run.log"

[MCMC]
  generations = "150000000001"
  full_update_freq = 200
  alignment_sample_frequency = 5000000
  position_sample_count = 175
  output_frequency = 1100000
  print_frequency = 50000
  triple_recursion = false
  base_virtual = 100
  include_alternative_domain = true

[MODEL]
  script_file = "intrinsic_order_model.lua"

  #Primary states.
  states = ["A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"]
  sequences_file = "dataset/G1LLZ1_Archaea.fasta"

  sequences_out_file = "aa_sequences.fasta"
  substitutions_out_file = "aa_substitutions.csv"

  # Intrinsic Order/Disorder States.
  intrinsic_order_states = ["O", "D" ]
  intrinsic_order_sequences_file = "dataset/G1LLZ1_Archaea.iupred.io_prediction.efasta"

  intrinsic_order_sequences_out_file = "intrinsic_order_sequences.fasta"
  intrinsic_order_substitutions_out_file = "intrinsic_order_substitutions.csv"

  # Constraints
  rare_substitutions_file = "dataset/rare_substitutions.txt"
  uninformative_substitutions_file = "dataset/uninformative_substitutions.txt"

  # Parameters
  step_size = 0.00001
  intrinsic_order_transition = 0.065
