debug = true
seed = 23241234

# Tree Settings
[TREE]
  max_segment_probability = 0.08
  branch_split_algorithm = 1
  scale_tree = false
  target_tree_length = 100.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  sample_frequency = 2000
  refresh_tree_on_update = true
  initial_value = 0.2
  threshold = 0.01
  max_step = 0.005

[INPUT]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  tree_file = "data_sets/tree.newick"

[OUTPUT]
  output_directory = "/output"
  output_directory_append_time = false
  overwrite_output = true
 
  tree_out_file = "tree_out.newick"
  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_counts_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  counts_out_file = "counts.csv"
  log_out_file = "run.log"

[MCMC]
  #generations = "1000001"
  generations = "1000000"
  position_sample_count = 6
  full_update_freq = 100
  alignment_sample_frequency = 2500
  output_frequency = 1000
  print_frequency = 1000
  triple_recursion = true
  rare_threshold = 0.001

[MODEL]
  script_file = "2_basic_model.lua"

  sequences_file = "data_sets/nucleotide_single.fasta"

  sequences_out_file = ""
  substitutions_out_file = "substitutions.out"

  step_size = 0.0005
  states = ['a', 't', 'c', 'g']