debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_probability = 0.05
  branch_split_algorithm = 1
  scale_tree = true
  target_tree_length = 1.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  sample_frequency = 2000
  refresh_tree_on_update = true
  initial_value = 0.5
  threshold = 0.01
  max_step = 0.005

[INPUT]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  tree_file = "data_sets/tree.newick"

[OUTPUT]
  output_directory = "/output"
  output_directory_append_time = false
  overwrite_output = true 

  tree_out_file = "tree_out.newick"
  parameters_out_file = "parameters_out.csv"
  parameters_counts_out_file = "parameters_counts_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  counts_out_file = "counts.csv"

[MCMC]
  generations = 2001
  #generations = 800
  full_update_freq = 200
  alignment_sample_frequency = 500
  output_frequency = 50
  print_frequency = 100

[MODEL]
  script_file = "7_hidden_states.lua"

  sequences_out_file = "sequences_out.fasta"

  substitutions_out_file = "substitutions.out"
  sequences_file = "data_sets/nucleotide.fasta"

  step_size = 0.001
  states = ['a', 't', 'c', 'g']
