debug = true
seed = 0

# Tree Settings
[TREE]
  max_segment_length = 0.08
  branch_split_algorithm = 1
  scale_factor = 1.0
  resolve_multifurcation = true

# Uniformization Constant
[UNIFORMIZATION]
  dynamic = false
  sample_frequency = 2000
  refresh_tree_on_update = true
  initial_value = 0.5
  threshold = 0.01
  max_step = 0.005

[DATA]
  # This should be TRUE or FALSE
  ancestral_sequences = false
  substitution_model_file = "model_GNR.lua"

  #sequences_file = "co1.fasta"
  sequences_file = "co1_reduced.fasta"
  #tree_file = "co1.newick"
  tree_file = "mito.newick"
[OUTPUT]
  output_directory = "/output"
  tree_out_file = "tree_out.newick"
  #sequences_out_file = "sequences_out.fasta"
  sequences_out_file = ""
  parameters_out_file = "parameters_out.csv"
  rate_vectors_out_file = "rate_vectors_out.csv"
  likelihood_out_file = "likelihoods_out.csv"
  substitutions_out_file = "substitutions.out"
  counts_out_file = "counts.csv"
  log_out_file = "run.log"

[MCMC]
  generations = 10000001
  #generations = 800
  full_update_freq = 200
  tree_sample_frequency = 70001
  tree_sample_n_positions = 10000
  output_frequency = 10000
  print_frequency = 10000

[MODEL]
  states = ["A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"]
  num_categories = 10
  #parameter_type = "continuous"
